apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: r-place
type: Opaque
stringData:
  POSTGRES_DB:       rplace
  POSTGRES_USER:     rplace_user
  POSTGRES_PASSWORD: R_place_S3cur3!
